name: 'Terraform Initialization'
description: 'Install and Initialization of Terraform'

inputs:
  cloud-tf:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Initialization Output
      id: initialization
      shell: bash
      run: |
        echo "value= ${{ inputs.cloud-tf }}"
    - name: terraform cloud
      if: ${{ inputs.cloud-tf == 'true' }}
      shell: bash
      run: |
        echo "terrafrom-cloud-one"

    - name: terraform free
      if: ${{ inputs.cloud-tf == 'false' }}
      shell: bash
      run: |
        echo "terrafrom-free-one"