name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
outputs:
  pre_commit_output:
    description: The output of the pre-commit run
    value: ${{ steps.run_pre_commit.outputs.pre_commit_output }}
runs:
  using: composite
  steps:
  - run: python -m pip install pre-commit
    shell: bash
  - run: python -m pip freeze --local
    shell: bash
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - id: run_pre_commit
    run: |
      output=$(pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }} | tee /dev/tty)
      echo "pre_commit_output<<EOF" >> $GITHUB_OUTPUT
      echo "${output}" >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT
    shell: bash




# name: pre-commit
# description: run pre-commit
# inputs:
#   extra_args:
#     description: options to pass to pre-commit run
#     required: false
#     default: '--all-files'
# runs:
#   using: composite
#   steps:
#   - run: python -m pip install pre-commit
#     shell: bash
#   - run: python -m pip freeze --local
#     shell: bash
#   - uses: actions/cache@v4
#     with:
#       path: ~/.cache/pre-commit
#       key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
#   - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
#     shell: bash
