name: terraform-build

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform_directory:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      jira-key:
        required: false
        type: string
      ARM_CLIENT_ID:
        required: false
        type: string
      destroy:
        required: false
        type: string
    
    secrets:
      ARM_CLIENT_ID :
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      token:
        required: true

            
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      
      - name: all variables
        run:  env

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Terraform Directory Path
        id: concatenate
        run: echo "terraformdirectory=${{ github.workspace }}/${{ inputs.terraform_directory }}" >> $GITHUB_OUTPUT   
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ steps.concatenate.outputs.terraformdirectory }}
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'vinayprakash893/azure-terraform-actions-reusable'
          ref: main
          #token: ${{ secrets.API_GITHUB_TOKEN }}
          path: 'reusable-workflows-path'
      
      # - name: shell
      #   run:  |
      #     env
      #     ls -l
      #     pwd

      #TERRAFORM COMMANDS
      

      # - name: shell2
      #   run:  |
      #     env
      #     ls -l
      #     pwd

      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
        id: validate
        with:
          working-directory: ${{ steps.concatenate.outputs.terraformdirectory }}
          extra_args: '--all-files 2>&1 | tee precommit_output.txt'
        continue-on-error: true

      - name: Print captured output
        id: capture_file
        run: |
          # echo "The pre-commit output was:"
          # cat precommit_output.txt
          file_content=$(cat precommit_output.txt)
          # echo "$file_content"
          echo "file_content=$file_content" >> $GITHUB_OUTPUT
      # - name: Terraform fmt
      #   id: fmt
      #   run: terraform fmt -check
      #   continue-on-error: true
      
      # - name: Validate Terraform code
      #   id: validate
      #   shell: bash
      #   run: terraform validate 
      #   working-directory: ${{ steps.concatenate.outputs.terraformdirectory }}

      - name: Terraform Initialization
        id: terraform-init
        uses: ./reusable-workflows-path/actions
        with:
          working-directory: ${{ steps.concatenate.outputs.terraformdirectory }}
          cli_token: ${{ secrets.TF_API_TOKEN }}
        env:
          #ARM_CLIENT_ID:       ${{ inputs.ARM_CLIENT_ID }}
          ARM_CLIENT_ID:       ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:       ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}

      - name : Print Title of PR
        env:
            TITLE: ${{ github.event.pull_request.title }}
        run: echo The Title of your PR is $TITLE
      
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.REPO_SCOPED_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.terraform-init.outputs.init-status }}\`
            #### Check Terraform state file 🔎:  \`${{ steps.terraform-init.outputs.state-check }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.capture_file.outputs.file_content }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ steps.concatenate.outputs.terraformdirectory  }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

      
      - name: get the comment-message
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
            MESSGE: ${{ github.event.head_commit.message }}
        run: |
          echo Merge Message is: $MESSGE
          number=$(echo $MESSGE | grep -oP 'pull request #\K\d+'|| true)
          if [ -z "$number" ]; then
              echo "No pull request number found."
              PR_Number=''
              echo "PR_Number=$PR_Number" >> $GITHUB_ENV
          else
              echo "Pull request number: $number"
              PR_Number=$number
              echo "PR_Number=$PR_Number" >> $GITHUB_ENV
          fi
          exit 0
      
      - name: print commit number
        if: env.PR_Number != ''
        run: |
          echo "$PR_Number"
        
      - name: Add comment message in PR
        if: env.PR_Number != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_SCOPED_TOKEN }}
          script: |
            const prNumber = process.env.PR_Number;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Main branch comment'
            })


      - name: Add failed message in PR
        if: ${{ failure() }}
        uses: actions/github-script@v6
        # env:
        #   APPLY: "terraform\n${{ steps.terraform-apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.REPO_SCOPED_TOKEN }}
          script: |
            let number = null ;
            if (context.eventName === 'pull_request') {
              number = context.payload.pull_request.number;
            } 
            else if (context.eventName === 'push') {
              const commitSHA = context.sha;
              const { data: listPullRequestsAssociatedWithCommit } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commitSHA,
              });
              if (listPullRequestsAssociatedWithCommit.length === 0) {
                console.log("The list is empty. No number available");
                } else {
                number = listPullRequestsAssociatedWithCommit[0].number;
              }
            }
            
            if (number){
            console.log('Issue or Pull Request Number:', number);
              github.rest.issues.createComment({
                issue_number: number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Failed, Please check the logs  ${{ steps.capture_file.outputs.file_content }}'
              })
            } else { console.log('No Issue or Pull Request associated with this event.'); }

